//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 AdbController.rc 使用
//
#define IDC_BREAK                       3
#define IDC_KILL                        4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ADBCONTROLLER_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       131
#define IDD_PACKAGE_DIALOG              132
#define IDC_REUSE                       1000
#define IDC_COMMAND                     1001
#define IDC_OUTPUT                      1002
#define IDC_M_DEVICE_ID                 1003
#define IDC_S1_DEVICE_ID                1004
#define IDC_S2_DEVICE_ID                1005
#define IDC_S3_DEVICE_ID                1006
#define IDC_S4_DEVICE_ID                1007
#define IDC_M_TOUCH_EVT                 1008
#define IDC_S1_TOUCH_EVT                1009
#define IDC_S2_TOUCH_EVT                1010
#define IDC_S3_TOUCH_EVT                1011
#define IDC_S4_TOUCH_EVT                1012
#define IDC_M_SYNC_CHK                  1013
#define IDC_S1_SYNC_CHK                 1014
#define IDC_S2_SYNC_CHK                 1015
#define IDC_S3_SYNC_CHK                 1016
#define IDC_S4_SYNC_CHK                 1017
#define IDC_M_DEVICE_BTN                1018
#define IDC_S1_DEVICE_BTN               1019
#define IDC_S2_DEVICE_BTN               1020
#define IDC_S3_DEVICE_BTN               1021
#define IDC_S4_DEVICE_BTN               1022
#define IDC_M_TOUCH_EVT_BTN             1023
#define IDC_S1_TOUCH_EVT_BTN            1024
#define IDC_S2_TOUCH_EVT_BTN            1025
#define IDC_S3_TOUCH_EVT_BTN            1026
#define IDC_S4_TOUCH_EVT_BTN            1027
#define IDC_CMD_OUT_CLEAR               1028
#define IDC_STATUS_OUT_CLEAR            1029
#define IDC_STATUS_OUTPUT               1030
#define IDC_M_PLAY_SCRIPT_BTN           1031
#define IDC_S1_PLAY_SCRIPT_BTN          1032
#define IDC_S2_PLAY_SCRIPT_BTN          1033
#define IDC_S3_PLAY_SCRIPT_BTN          1034
#define IDC_S4_PLAY_SCRIPT_BTN          1035
#define IDC_M_SCRIPT_FILE               1036
#define IDC_S1_SCRIPT_FILE              1037
#define IDC_S2_SCRIPT_FILE              1038
#define IDC_S3_SCRIPT_FILE              1039
#define IDC_S4_SCRIPT_FILE              1040
#define IDC_CONNECT_DEVICES             1041
#define IDC_CONNECT_DEVICES2            1042
#define IDC_DISCONNECT_DEVICES          1042
#define IDC_CENTER_X                    1043
#define IDC_CENTER_Y                    1044
#define IDC_POINT_X                     1045
#define IDC_MOVE_OFFSET                 1046
#define IDC_MOVE_DURATION               1047
#define IDC_MOVE_UP                     1048
#define IDC_MOVE_LEFT                   1049
#define IDC_MOVE_LEFT_UP                1050
#define IDC_MOVE_LEFT_UP_UP             1051
#define IDC_MOVE_LEFT_UP_DW             1052
#define IDC_MOVE_LEFT_DW                1053
#define IDC_MOVE_LEFT_DW_UP             1054
#define IDC_MOVE_LEFT_DW_DW             1055
#define IDC_MOVE_RIGHT                  1056
#define IDC_MOVE_RIGHT_UP               1057
#define IDC_MOVE_RIGHT_UP_UP            1058
#define IDC_MOVE_RIGHT_UP_DW            1059
#define IDC_MOVE_RIGHT_DW               1060
#define IDC_MOVE_RIGHT_DW_UP            1061
#define IDC_MOVE_RIGHT_DW_DW            1062
#define IDC_MOVE_DOWN                   1063
#define IDC_SYNC_MOVE_MASTER            1064
#define IDC_SYNC_MOVE_SLAVE_1           1065
#define IDC_SYNC_MOVE_SLAVE_2           1066
#define IDC_SYNC_MOVE_SLAVE_3           1067
#define IDC_SYNC_MOVE_SLAVE_4           1068
#define IDC_DEGREE                      1069
#define IDC_MOVE_DEGREE                 1070
#define IDC_CENTER_Y2                   1071
#define IDC_POINT_Y                     1072
#define IDC_MOVE_XY                     1073
#define IDC_PKG_START_X                 1074
#define IDC_PKG_START_Y                 1075
#define IDC_PKG_INV_W                   1076
#define IDC_PKG_INV_H                   1077
#define IDC_PACKAGE_BTN1                1078
#define IDC_PACKAGE_BTN2                1079
#define IDC_PACKAGE_BTN3                1080
#define IDC_PACKAGE_BTN4                1081
#define IDC_PACKAGE_BTN5                1082
#define IDC_PACKAGE_BTN6                1083
#define IDC_PACKAGE_BTN7                1084
#define IDC_PACKAGE_BTN8                1085
#define IDC_PACKAGE_BTN9                1086
#define IDC_PACKAGE_BTN10               1087
#define IDC_PACKAGE_BTN11               1088
#define IDC_PACKAGE_BTN12               1089
#define IDC_PACKAGE_BTN13               1090
#define IDC_PACKAGE_BTN14               1091
#define IDC_PACKAGE_BTN15               1092
#define IDC_PACKAGE_BTN16               1093
#define IDC_PACKAGE_BTN17               1094
#define IDC_PACKAGE_BTN18               1095
#define IDC_PACKAGE_BTN19               1096
#define IDC_PACKAGE_BTN20               1097
#define IDC_PACKAGE_CHECK1              1098
#define IDC_PACKAGE_CHECK2              1099
#define IDC_PACKAGE_CHECK3              1100
#define IDC_PACKAGE_CHECK4              1101
#define IDC_PACKAGE_CHECK5              1102
#define IDC_PACKAGE_CHECK6              1103
#define IDC_PACKAGE_CHECK7              1104
#define IDC_PACKAGE_CHECK8              1105
#define IDC_PACKAGE_CHECK9              1106
#define IDC_PACKAGE_CHECK10             1107
#define IDC_PACKAGE_CHECK11             1108
#define IDC_PACKAGE_CHECK12             1109
#define IDC_PACKAGE_CHECK13             1110
#define IDC_PACKAGE_CHECK14             1111
#define IDC_PACKAGE_CHECK15             1112
#define IDC_PACKAGE_CHECK16             1113
#define IDC_PACKAGE_CHECK17             1114
#define IDC_PACKAGE_CHECK18             1115
#define IDC_PACKAGE_CHECK19             1116
#define IDC_PACKAGE_CHECK20             1117
#define IDC_PACKAGE_M                   1120
#define IDC_PACKAGE_S1                  1121
#define IDC_PACKAGE_S2                  1122
#define IDC_PACKAGE_S3                  1123
#define IDC_PACKAGE_S4                  1124
#define IDC_PACKAGE_TAKE_BTN            1125
#define IDC_PACKAGE_CLEAR_BTN           1126
#define IDC_STATIC_PKD_ID               1127
#define IDC_PREVIOUS_THING              1128
#define IDC_NEXT_THING                  1129
#define IDC_CLEAR_THING                 1130
#define IDC_OPEN_THING              	1131

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
